## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
 allow_failures:
 - julia: nightly
notifications:
  email: false
codecov: true
env:
  global:
    - OMP_NUM_THREADS=1
